name: CI

on: [pull_request]

env:
  JET_DISTRIBUTED_CACHE_ENABLED: false

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump env context
        shell: cmd
        run: env
      - name: Cache Build JVM
        id: cache-gradle-jvm
        uses: actions/cache@v2
        with:
          path: rider/build/gradle-jvm
          key: ${{ runner.os }}-gradle-jvm-${{ hashFiles('rider/build.gradle') }}
      - name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('rider/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle dependencies
        id: cache-gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            !~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea
            !~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider
          key: ${{ runner.os }}-gradle-test2-${{ hashFiles('rider/**/?*.gradle*') }}
      - name: Cache test packages
        id: cache-test-packages
        uses: actions/cache@v2
        with:
          path: ~/JetTestPackages
          key: ${{ runner.os }}-jet-test-packages-${{ hashFiles('~/JetTestPackages/**/*.nupkg') }}
          restore-keys: ${{ runner.os }}-jet-test-packages-
      - name: Dump Gradle
        run: tree C:\Users\runneradmin\.gradle /f /a
      - name: Dump build dir
        run: tree rider\build /f /a
      - name: Build and Run Tests
        shell: powershell
        run: |
          $env:JET_TEST_PACKAGES_DIR=$HOME + '\JetTestPackages'
          .\build.ps1 -RunTests -Verbose
      - name: Stop gradle daemons
        run: rider/gradlew.bat --stop
      - name: Dump Gradle 2
        run: tree C:\Users\runneradmin\.gradle /f /a
      - name: Dump build dir 2
        run: tree rider\build /f /a
      - name: Dump JetTestPackages
        run: tree C:\Users\runneradmin\JetTestPackages
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: ./build.sh --info --stacktrace

